// <auto-generated />
namespace PickMyBeer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2ms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2ms));
        
        string IMigrationMetadata.Id
        {
            get { return "201703151927418_m2ms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
